### ISSUE TITLE
different docker files/images/containers per AWS account

### ISSUE THREAD

**Issue by lotharschulz** [zalando/ghe-backup#40]
Current situation: backups in both AWS accounts are triggered via corn at the same time 13th minutes.
goals: 
* backups should be triggered in one account on odd hours in the other account in even hours
  * approach: different dockerfiles, docker images, docker container per AWS account
* trigger the backup process only if no other backup process is in the process list

**Comment by lotharschulz** [comment]
FYI: @rashamalek

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/41 targets goal one

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/41 stabilized the situation

**Comment by lotharschulz** [comment]
test deployment ended up with:
```
root@9031658457e9:/backup# /trigger_ghebackup.py
bash: /trigger_ghebackup.py: Permission denied
```

**Comment by lotharschulz** [comment]
* PR https://github.com/zalando/ghe-backup/pull/43 merged.
* will close this after successful deployments

**Comment by lotharschulz** [comment]
* all backup attempts failing right now
* working assumption is: backups are affected as the replication is not complete currently

**Comment by lotharschulz** [comment]
process list:
```
...
root      6081  0.0  0.0  45804   388 ?        S    Mar14   0:00  \_ CRON
root      6082  0.0  0.0   4508    72 ?        Ss   Mar14   0:00      \_ /bin/sh -c /start_backup.sh
root      6083  0.0  0.0   9568   224 ?        S    Mar14   0:00          \_ /bin/bash /start_backup.sh
root      6085  0.0  0.0   9672   328 ?        S    Mar14   0:00              \_ bash /backup/backup-utils/bin/ghe-backup -v
root      6633  0.0  0.0   9696   356 ?        S    Mar14   0:00                  \_ bash /backup/backup-utils/share/github-backup-utils/ghe-backup-repositories-rsync
root      6732  0.0  0.0   9660   272 ?        S    Mar14   0:00                      \_ bash /backup/backup-utils/share/github-backup-utils/ghe-rsync -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=- --exclu
root      6739  0.0  0.0   9660   304 ?        S    Mar14   0:00                          \_ bash /backup/backup-utils/share/github-backup-utils/ghe-rsync -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=- --e
root      6742  0.0  0.8 137428  8680 ?        S    Mar14   0:02                          |   \_ rsync --bwlimit=4000 -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=- --exclude=* ....:/data/us
root      6745  0.0  0.0  47240   976 ?        S    Mar14   0:00                          |   |   \_ ssh -p 22 -l admin -o StrictHostKeyChecking=no -p 122 -o BatchMode=yes ....  -- nice -n 19 ionice -c 3 sudo -u git rsync --server --sender -vlogDtprze.iLsf
root      6759  0.0  0.8 226920  9060 ?        S    Mar14   0:00                          |   |   \_ rsync --bwlimit=4000 -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=- --exclude=* ....:/dat
root      6743  0.0  0.0   9660   296 ?        S    Mar14   0:00                          |   \_ bash /backup/backup-utils/share/github-backup-utils/ghe-rsync -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=-
root      6744  0.0  0.0  11284   104 ?        S    Mar14   0:00                          |       \_ grep -E -v ^(file has vanished: |rsync warning: some files vanished before they could be transferred)
root      6740  0.0  0.0   9660   304 ?        S    Mar14   0:00                          \_ bash /backup/backup-utils/share/github-backup-utils/ghe-rsync -av -e ghe-ssh -p 122 --link-dest=../../current/repositories -z --rsync-path=sudo -u git rsync --include-from=- --e
root      6741  0.0  0.0  11284   100 ?        S    Mar14   0:00                              \_ grep -E -v ^(file has vanished: |rsync warning: some files vanished before they could be transferred)
```

vanished file message most likely is cause by https://github.com/github/backup-utils/blob/5632cc542cf93f27c5a4534253049e386783bd53/share/github-backup-utils/ghe-rsync#L16.

A similar issue was tracked in https://github.com/zalando/ghe-backup/issues/27 - this one's solution was the [stabilized the master](https://github.com/zalando/ghe-backup/issues/27#issuecomment-247040957). Thats why I hope backups are going to work if the replication is also complete.

**Comment by rashamalek** [comment]
Probably the issue is related to the bandwidth restriction "rsync --bwlimit=xxxx ..." .
https://github.com/github/backup-utils/pull/161 indicates that the current limit is 4000 KB/s
While --bwlimit parameter is a KB/second value, It means that at most, around 13,7GB would be transferred , in an hour.
When it comes to small files rsync over ssh [probably every other script] is totally slow.
For a fresh backup it tries to sync more than 80GB, and more than 300K files.

**Comment by lotharschulz** [comment]
just discussed with @rashamalek to remove the bwlimit for now and monitor the next backup.

**Comment by lotharschulz** [comment]
related: https://github.com/zalando/ghe-backup/issues/49

**Comment by lotharschulz** [comment]
set new `bwlimit=30000` based on the [bwlimit calculation](https://github.com/zalando/ghe-backup/files/858672/bwlimit.calculation.pdf) that is based on the observations @rashamalek did before filing #49

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/50 changes deployed, will check backups tomorrow.

**Comment by lotharschulz** [comment]
backups successful on both accounts, [bus](https://github.com/zalando/ghe-backup/blob/master/cron-ghe-backup-bus) and [automata](https://github.com/zalando/ghe-backup/blob/master/cron-ghe-backup-automata).
