### ISSUE TITLE
backup schedule overlap 

### ISSUE THREAD

**Issue by rashamalek** [zalando/ghe-backup#49]
Hi,
Currently [cron-ghe-backup-automata](https://github.com/zalando/ghe-backup/blob/master/cron-ghe-backup-automata) and [cron-ghe-backup-bus](https://github.com/zalando/ghe-backup/blob/master/cron-ghe-backup-bus) each, are configured for every two hours.
First automata backup took more than 1 hour. the next one took around 13 minutes.
This would lead us not to able to calculate the normal backup, and an overlap between automata and bus backup instances.
Suggestion: change the cron to every 3-4 hours to prevent the overlap, and also some time for GHE job queue to be cleaned and completed.
@lotharschulz Please check if applicable.

`
$ du -hc --max-depth=1 /data/ghe-production-data
124G	/data/ghe-production-data/20170321T121301
12G	/data/ghe-production-data/20170321T101301
`

**Comment by lotharschulz** [comment]
> Suggestion: change the cron to every 3-4 hours to prevent the overlap, and also some time for 
> GHE job queue to be cleaned and completed.
sounds like a reasonable conclusion. Lets do that.

For the records, https://github.com/github/backup-utils#scheduling-backups recommends currently  hourly backups.
