### ISSUE TITLE
ghe-backup-volume could not be mounted again after a failure/termination or stop

### ISSUE THREAD

**Issue by rashamalek** [zalando/ghe-backup#75]
If ec2 instance is stopped or terminates, autoscalinggroup spins up a new instance, but
ghe-backup-volume will not be mounted, and taupage scripts fail.

**Comment by lotharschulz** [comment]
Turned out taupage volume scanning needs more memory than [t2.small](http://www.ec2instances.info/?selected=t2.small) provides. Upgrading to [t2.medium](http://www.ec2instances.info/?selected=t2.medium) solved the issue.
