### ISSUE TITLE
make kms decryption region a parameterised information

### ISSUE THREAD

**Issue by lotharschulz** [zalando/ghe-backup#83]
remove hard coded AWS region: 
https://github.com/zalando/ghe-backup/blob/master/convert-kms-private-ssh-key.sh#L36

**Comment by rashamalek** [comment]
based on [Instance Identity Documents](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html)
  we can extract an instance using [document endpoint](http://169.254.169.254/latest/dynamic/instance-identity/document) 

```
REGION=`curl http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}'`
sed  "s/eu-central-1/$REGION/g" /kms/convert-kms-private-ssh-key_original.sh
```

Simple and quickest solution would be to replace it in the /kms/convert-kms-private-ssh-key.sh file using sed
