### ISSUE TITLE
be DRY - create ONE function writing the ssh private key for both, Kubernetes & AWS/Taupage

### ISSUE THREAD

**Issue by lotharschulz** [zalando/ghe-backup#86]
- https://github.com/zalando/ghe-backup/issues/83 follow up
- https://github.com/zalando/ghe-backup/blob/master/convert-kms-private-ssh-key.sh#L36

**Comment by shamshev** [comment]
hi @lotharschulz,

https://github.com/shamshev/ghe-backup/blob/feature/issue_86/convert-kms-private-ssh-key.sh

**Comment by lotharschulz** [comment]
Thanks @shamshev !

Looks good to me - just from reading your code.
Matter of taste: https://github.com/shamshev/ghe-backup/blob/feature/issue_86/convert-kms-private-ssh-key.sh#L43 could use several lines so readers can grasp quickly what the intention is.

Apart from that, [I](https://github.com/lotharschulz) am not part of the [zalando github organisation](https://github.com/zalando/) anymore. I can't judge how worth the effort is for people at zalando currently working on this. You can contact one of the [MAINTAINERS](https://github.com/zalando/ghe-backup/blob/master/MAINTAINERS).
