### ISSUE TITLE
delivery.yaml in k8s-master-like and master branch

### ISSUE THREAD

**Issue by rashamalek** [zalando/ghe-backup#87]
@lotharschulz 
Here is my understanding of "k8s-master-like" and "master" branches
"k8s-master-like" branch: Its [delivery.yaml](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml
) should build and push an k8s compatible image to pierone,  

"master" branch: its [delivery.yaml](https://github.com/zalando/ghe-backup/blob/master/delivery.yaml
) should build and push a Taupage compatible image to pierone,  

are these definitions mixed somehow?

Currently 
[k8s-master-like/delivery.yaml#L18](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L18) and [k8s-master-like/delivery.yaml#L27](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L27) seem to be creating Taupage compatible ones, and
[master/delivery.yaml#L22](https://github.com/zalando/ghe-backup/blob/master/delivery.yaml#L22) 
is creating a k8s compatible one.

**Comment by lotharschulz** [comment]
I propose to rely on the docker images produced in https://github.com/zalando/ghe-backup/blob/master/delivery.yaml#L22 _only_. The docker image name might be misleading, its actually meant to run on both, Kubernetes clusters and AWS/Taupage. What about 
`BASE_IMAGE=$PIERONE_NAMESPACE/ghe-backup` ?

In case we need images like
- [IMAGE=pierone.stups.zalan.do/machinery/ghe-backup-bus:cdp-${CDP_BUILD_VERSION}](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L18)
- [IMAGE=pierone.stups.zalan.do/machinery/ghe-backup-automata:cdp-${CDP_BUILD_VERSION}](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L27)

I'd raise a PR to add it the ["build and push docker images"](https://github.com/zalando/ghe-backup/blob/master/delivery.yaml#L20-L32).

Do you see value in keeping the [_k8s-master-like_ branch](https://github.com/zalando/ghe-backup/tree/k8s-master-like)?

**Comment by lotharschulz** [comment]
@rashamalek and me agreed to:

- [x]  delete [_k8s-master-like_ branch](https://github.com/zalando/ghe-backup/tree/k8s-master-like)
  - images like 
     - [IMAGE=pierone.stups.zalan.do/machinery/ghe-backup-bus:cdp-${CDP_BUILD_VERSION}](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L18)
     - [IMAGE=pierone.stups.zalan.do/machinery/ghe-backup-automata:cdp-${CDP_BUILD_VERSION}](https://github.com/zalando/ghe-backup/blob/k8s-master-like/delivery.yaml#L27)

     won't be built anymore

- [ ] I am going to raise PR to rename the docker image to `BASE_IMAGE=$PIERONE_NAMESPACE/ghe-backup` (https://github.com/zalando/ghe-backup/blob/master/delivery.yaml#L22)
