### ISSUE TITLE
correct permissions for /kms/convert-kms-private-ssh-key.sh

### ISSUE THREAD

**Issue by rashamalek** [zalando/ghe-backup#93]
Permission issues on /kms/convert-kms-private-ssh-key.sh
May 30 13:02:46 ip-172-31-142-237 docker/d13c786d96fd[825]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 30 13:02:46 ip-172-31-142-237 docker/d13c786d96fd[825]:                                  Dload  Upload   Total   Spent    Left  Speed
May 30 13:02:46 ip-172-31-142-237 docker/d13c786d96fd[825]: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   469  100   469    0     0   114k      0 --:--:-- --:--:-- --:--:--  114k
May 30 13:02:46 ip-172-31-142-237 docker/d13c786d96fd[825]: /backup/final-docker-cmd.sh: line 14: /kms/convert-kms-private-ssh-key.sh: Permission denied

**Comment by rashamalek** [comment]
@lotharschulz 
https://github.com/zalando/ghe-backup/blob/master/final-docker-cmd.sh#L13 ( actually
https://github.com/zalando/ghe-backup/blob/master/replace-convert-properties.sh#L19 ) is causing the permission of  /kms/convert-kms-private-ssh-key.sh to change to rw only:

```
application@46d4e8f09099:~$ ls -ltra /kms/convert-kms-private-ssh-key.sh
-rwx------ 1 application application 2246 May 30 12:55 /kms/convert-kms-private-ssh-key.sh

```

Here is what happens when /backup/final-docker-cmd.sh executes:

```
application@46d4e8f09099:~$ /backup/final-docker-cmd.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469  100   469    0     0  93800      0 --:--:-- --:--:-- --:--:--  114k
/backup/final-docker-cmd.sh: line 14: /kms/convert-kms-private-ssh-key.sh: Permission denied

application@46d4e8f09099:~$ ls -ltra /kms/convert-kms-private-ssh-key.sh
-rw-r--r-- 1 application application 2243 May 30 15:46 /kms/convert-kms-private-ssh-key.sh
```

Either we can use "sed -i" to replace the string in-place, or to add `chmod +x /kms/convert-kms-private-ssh-key.sh` afterwards to add the permission back to /kms/convert-kms-private-ssh-key.sh 


I still think "sed -i" is better, and we can find a way to fix the issue of local tests on Mac. @lotharschulz any thoughts?

**Comment by lotharschulz** [comment]
I prefer the `sed -i` approach.
